version: "3.9"
services:
  notifications:
    container_name: notifications
    image: taller3-notificaciones
    ports:
      - '9002:9069'
    environment:
      - PORT=9069
      - LOG_LEVEL=INFO
      - secret="no me usan bien"
      - algorithm=HS256
      - TELEGRAM_SECRET=TeEstasPortandoMal
      - TELEGRAM_ACCESS_CODE=SerasCastigada
    networks:
      - taller3-network

networks:
  taller3-network:
    name: taller3-network
    external: true