version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=pets
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - taller3-network

  pets:
    container_name: pets
    image: taller3-mascotas
    ports:
      - "9001:9000"
    environment:
      - PORT=9000
      - DB_URL=postgres://admin:admin@postgres:5432/pets?sslmode=disable
      - secret="jamas me usan bien"
      - algorithm=HS256
      - TREATMENTS_URL=http://treatments:9000/treatments/application/pet
      - USERS_URL=http://users:9000/users/telegram_id
    depends_on:
      postgres:
        condition: service_healthy
    networks:
        - taller3-network

networks:
  taller3-network:
    name: taller3-network
