version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=pets
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - taller3-network

  pets:
    container_name: pets
    image: back-mascotas
    ports:
      - "9001:9000"
    environment:
      - PORT=9000
      - DB_URL=postgres://admin:admin@postgres:5432/pets?sslmode=disable
    depends_on:
      - postgres
    networks:
        - taller3-network

networks:
  taller3-network:
    name: taller3-network