version: "3.8"
services:
  users:
    image: taller3-usuarios
    container_name: users
    ports:
      - "9005:9000"
    environment:
       - PORT=9000
       - DB_URL=postgres://admin:admin@postgres:5432/pets?sslmode=disable
       - secret="jamas me usan bien"
       - algorithm=HS256
    networks:
      - taller3-network

networks:
  taller3-network:
    name: taller3-network
    external: true
