version: '3.9' # optional since v1.27.0
services:
  dynamo:
    container_name: dynamo
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    command: '-jar DynamoDBLocal.jar -sharedDb'
    networks:
      - taller3-network

  treatments:
    container_name: treatments
    image: taller3-tratamientos
    depends_on:
      - dynamo
    ports:
      - "9004:9000"
    environment:
      - PORT=9000
      - DYNAMO_ACCESS_KEY_ID=key
      - DYNAMO_SECRET_KEY_ID=secret
      - DYNAMO_REGION=us-east-2
      - DYNAMO_ENDPOINT=http://dynamo:8000
      - secret="jamas me usan bien"
      - algorithm=HS256

    networks:
      - taller3-network

networks:
  taller3-network:
    name: taller3-network
    external: true
