version: "3.9"
services:
  telegram:
    container_name: telegram-bot
    image: taller3-telegram
    ports:
      - '6969:6969'
    environment:
      - LOG_LEVEL=INFO
      - SECRET=TeEstasPortandoMal
      - ALGORITHM=HS256
      - ACCESS_CODE=SerasCastigada

    networks:
      - taller3-network

networks:
  taller3-network:
    name: taller3-network
    external: true
