version: "3.9"
services:
  telegram:
    container_name: telegram
    image: taller3-telegram
    ports:
      - '6969:6969'
    environment:
      - LOG_LEVEL=INFO
      - SECRET=TeEstasPortandoMal
      - ALGORITHM=HS256
      - ACCESS_CODE=SerasCastigada
      - TELEGRAM_BOT_TOKEN=6542890982:AAEHiy4I-GDFVqVu-0s00fjmgb7m4idoXKA

    networks:
      - taller3-network

networks:
  taller3-network:
    name: taller3-network
    external: true
